Document: v8cgi
Title: Debian v8cgi Manual
Author: <insert document author here>
Abstract: This manual describes what v8cgi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/v8cgi/v8cgi.sgml.gz

Format: postscript
Files: /usr/share/doc/v8cgi/v8cgi.ps.gz

Format: text
Files: /usr/share/doc/v8cgi/v8cgi.text.gz

Format: HTML
Index: /usr/share/doc/v8cgi/html/index.html
Files: /usr/share/doc/v8cgi/html/*.html
